name: CI-CD

on:
  push:
    branches: [main, dev]
    paths:
      - web/**
  pull_request:
    branches: [main, dev]
    paths:
      - web/**

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: html-gitops-eks
  EKS_CLUSTER: eks-gitops-cluster

jobs:
  BuildAndPublish:
    name: "Build docker image"
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: List content
        run: ls -a
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build and Push Image
        id: ecr-publish
        run: |
          IMAGE=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.run_number }}
          docker build -t $IMAGE -f ./web/Dockerfile ./web
          docker push $IMAGE
